# Generated by Django 3.0.8 on 2020-08-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='user_name',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
