# Generated by Django 3.0.8 on 2020-08-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_user_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_recipe',
            name='author',
            field=models.CharField(default='admin', max_length=16),
        ),
    ]
